import Header from "@/components/header/Header";
import "./globals.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Menu from "@/components/menu/Menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NTF",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header></Header>
        <div className="main">
          <Menu></Menu>
          <div className="container">{children}</div>
          <div className="spacer"></div>
        </div>
      </body>
    </html>
  );
}
